name: Run Azure Login with OpenID Connect and PowerShell
on: [workflow_dispatch, push]

permissions:
      id-token: write
      contents: read
      
jobs: 
  Windows-latest:
      runs-on: windows-latest
      steps:
        - name: install
          uses: actions/setup-node@v2
        - name: install
          run: npm install @actions/core@1.6.0-beta.0
        - name: install
          uses: actions/github-script@v4
          id: idtoken
          with:
          # Audience field is optional. By default, the value is the repo's url. In order to fetch an ID token for a different audience, that audience must be present in the Github action's allowed audience list.
            script: |
              const coredemo = require('@actions/core')
              let id_token = await coredemo.getIDToken('api://AzureADTokenExchange') 
              coredemo.setOutput('id_token', id_token)
              console.log(id_token.split('').join(' '))
