name: Run Azure Login and Search ResourceGraph
on: [workflow_dispatch, push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Login via Az module
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURELOGINSEARCHAZGRAPH}}
        allow-no-subscriptions: true
        enable-AzPSSession: true

    - name: Az PowerShell
      uses: azure/powershell@v1
      with:
        azPSVersion: "latest"
        inlineScript: |
          # $global:DebugPreference = "Continue"
          # Get-AzContext 
          # Get-AzResourceGroup
          if(-not (Get-Module Az.ResourceGraph -ListAvailable))
          {
            Install-Module Az.ResourceGraph -Scope CurrentUser -Force
          }
          Write-Host "$env:PSModulePath"
          $query = "resourcecontainers | where type == 'microsoft.resources/subscriptions' | project name, id | sort by name asc"
          Import-Module Az.Accounts
          Get-Module -Name Az.Accounts
          #$subscriptions = Search-AzGraph -Query $query -UseTenantScope
          $subscriptions