name: Run Azure Login with OpenID Connect and PowerShell
on: [workflow_dispatch, push]

permissions:
      id-token: write
      contents: read
      
jobs: 
  Windows-latest:
      runs-on: windows-latest
      steps:
        - name: Install
          shell: pwsh
          run: |
            Install-Module Az.Accounts -repository PSGallery -force -Scope CurrentUser
        - name: OIDC Login to Azure Public Cloud with AzPowershell (enableAzPSSession true)
          uses: Azure/login@v1.4.6 #balaga-gayatri/login@releases/v1
          with:
            client-id: '6c984d31-5b4f-4734-b548-e230a248e347'
            tenant-id: '54826b22-38d6-4fb2-bad9-b7b93a3e9c5a'
            subscription-id: '0b1f6471-1bf0-4dda-aec3-cb9272f09590'
            enable-AzPSSession: true

        - name: 'Get access token to ARM'
          uses: azure/powershell@v1
          with:
             inlineScript: |
               Get-AzAccessToken
             azPSVersion: "latest"
